version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: siimp-postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springboot:
    build: .
    container_name: siimp-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      # Can be used like the env VAR
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata:
